### PR TITLE
Now that SimpleLogin is fully open-source, move it to open-source section

### PR DESCRIPTION
**Pull request by nguyenkims**
…tion

### CODE REVIEW

**Comment by aaronpk** [comment]
It's not clear from the home page how this is an OAuth provider. Can you update the link to https://simplelogin.io/developer?

**Comment by nguyenkims** [comment]
Thanks, just updated the PR.

**Comment by nguyenkims** [comment]
@aaronpk is there other thing that I should update in the PR?

**Comment by aaronpk** [comment]
Looks good, thanks!

**Pull request merged**
