### PR TITLE
Add OAuth libraries

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by aaronpk** [comment]
Thanks! Just to confirm, all the okta libraries are generic OAuth clients, right? If they are, that's great. If they can only be used with Okta then I'm not sure they're a good fit for this page.

**Comment by aaronpk** [comment]
Were you ever able to find out if these libraries support other servers?

I recently reorganized the whole "code" page into separate pages per language, so this PR conflicts now. I'm happy to incorporate these links into the new format if you can confirm that they are generic libraries still!

**Comment by mraible** [comment]
No. I haven’t made the time to test these on another server like Keycloak. You can close this issue. I’ll open a new one after I’ve confirmed everything works.

**Comment by aaronpk** [comment]
ok. I've incorporated some of your other suggestions from here as well.

**Pull request closed without merging**
